name: 'dbt_vr_data'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_vr_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_vr_data:
    # Config indicated by + and applies to all files under models/{silver/gold}
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
